eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8081
spring:
    application:
        name: simple-service
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
default:
    security:
        includes: /api/simple/*
