eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8081
    servlet:
      context-path: /api
spring:
    application:
        name: simple-service
