eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8080
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true
          discovery:
              locator:
                  enabled: true
                  lower-case-service-id: true