eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8080
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
