eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8083
spring:
    application:
        name: reports-service
    resources:
        add-mappings: true
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
default:
    security:
        includes: /reports/api/reports/*
