eureka:
  client:
    serviceUrl:
      defaultZone: https://julia-eureka-service.herokuapp.com/eureka
server:
  port: ${PORT:8080}
spring:
  application:
    name: user-service
  resources:
    add-mappings: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
default:
  security:
    includes: /user/api/user/operations/*

