eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8081
spring:
    application:
        name: user-service
    resources:
        add-mappings: true
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
default:
    security:
        includes: /api/user/operations/*
