eureka:
  server:
    enableSelfPreservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://localhost:8080/eureka
server:
  port: 8080
spring:
  application:
    name: eureka-service