eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
server:
    port: 8082
spring:
    application:
        name: device-service
    resources:
        add-mappings: true
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
default:
    security:
        includes: /device/api/device/*
